RECAPTCHA_SECRET = '... reCAPTCHA secret here...'
DB = 'postgresql://username:password@localhost/tradeapi'
TEST_DB = 'postgresql://username:password@localhost/tradeapi_test'
BITCOIN = 'http://user:pass@127.0.0.1:8332'
MONERO_RPC_PASSWORD = 'password'
